name: dart_funcoes_colecoes
description: Modulo da Academia do Flutter de funções e coleções
version: 1.0.0
homepage: https://www.academiadoflutter.com.br

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
